// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/katsuokaisao/gorm/config"
	"github.com/katsuokaisao/gorm/infra/rdb"
	"github.com/katsuokaisao/gorm/infra/rdb/book"
	"github.com/katsuokaisao/gorm/usecase/gorm"
)

// Injectors from wire.go:

func SetApplication(cfg *config.Config) *Application {
	rdbConfig := provideRDBConfig(cfg)
	rdbRDB := rdb.NewRDB(rdbConfig)
	bookRepository := book.NewBookRepository(rdbRDB)
	bookReviewRepository := book.NewBookReviewRepository(rdbRDB)
	authorRepository := book.NewAuthorRepository(rdbRDB)
	gormUseCase := gorm.NewGormUseCase(bookRepository, bookReviewRepository, authorRepository)
	application := NewApplication(gormUseCase)
	return application
}
